version: '3.8'

services:
  web:
    build: .
    ports:
      - "8400:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=safevault_db
      - MASTER_KEY=${MASTER_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
    volumes:
      - ./app:/app/app

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
